# Use a secrets for storing secrets
# Base64 encode values stored in k8s secret:
apiVersion: v1
kind: Secret
metadata:
  name: envsecret
type: Opaque
data:
  APIKEY: XCSnmljsda34sdsa
  APIAUTH: {{ toYaml .Values.secrets.some_password | b64enc }}
