# -*- mode: ruby -*-
# vi: set ft=ruby :

# Development Vagrantfile example for Elasticsearch

# Elasticsearch Provision script
$elasticsearch_provision = <<-SHELL

  # Elasticsearch Major Version
  ES_VERSION="8.x"

  # update
  apt update
  apt install -y dirmngr    # optional

  # get elasticsearch GPG Key
  wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

  # select elasticsearch major version repo
  echo "deb https://artifacts.elastic.co/packages/$ES_VERSION/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch.list

  # install elasticsearch
  apt update && apt install -y elasticsearch

  # Update/Override Elasticsearch JVM Configs
  echo -e '-Xms1g\n-Xmx1g' > /etc/elasticsearch/jvm.options.d/overrides.options

  # start elasticsearch if it's not running
  service elasticsearch start
  service elasticsearch status

SHELL


Vagrant.configure("2") do |config|

  # define a server vagrant machine
  config.vm.define "eshost01", autostart: true do |eshost|

    # hostname for the VM
    eshost.vm.hostname = "eshost01-focal"
    # image for the VM
    # See all images at https://app.vagrantup.com/boxes/search
    eshost.vm.box = "ubuntu/focal64"

    # Use Virtual Box as the provider
    eshost.vm.provider "virtualbox" do |vb|
      #  Virtual Box Settings - GUI for the VM
      vb.gui = false
      #  Virtual Box Settings - Name for the VM
      vb.name = "Ubuntu 20.04 - Elasticsearch Server - 01"
      #  Virtual Box Settings - Allocated memory
      vb.memory = "3096"
    end

    # provision scripts
    eshost.vm.provision "shell", inline: $elasticsearch_provision

  end

end
