
services:
  dynamic-threadpool:
    container_name: dynamic-threadpool
    image: dynamic-threadpool
    command: ["-min", "1", "-max", "16", "-queue", "64", "-duration", "20s"]
    build:
      context: .
      dockerfile: ./Dockerfile
      target: pool
  dynamic-threadpool-help:
    container_name: dynamic-threadpool-help
    image: dynamic-threadpool
    command: ["-h"]
    build:
      context: .
      dockerfile: ./Dockerfile
      target: pool
