#!/bin/sh
# Prints the cluster config for the given storage replicasets (each: 2 instances, failover
# manual, the first is the leader) plus one router. NAME=W sets a replicaset's sharding weight
# (0 = drain it: the rebalancer moves all its buckets away).
#   sh scripts/config.sh a b        # 2 replicasets
#   sh scripts/config.sh a b c      # 3
#   sh scripts/config.sh a b c=0    # 3, storage-c draining
set -eu
cat <<'YAML'
# Generated by scripts/config.sh; `make` rewrites it and runs config:reload() on every instance.
credentials:
  users:
    replicator:
      password: secret
      roles: [replication]
    storage:                      # vshard router -> storage and storage -> storage (rebalancer)
      password: secret
      roles: [sharding]
      privileges:                 # the router's buckets() / check() call these directly
        - permissions: [execute]
          lua_call: [vshard.storage.info, kv_len, kv_missing]
    app:
      password: secret
      roles: [super]

iproto:
  advertise:
    peer:
      login: replicator
    sharding:
      login: storage

sharding:
  bucket_count: 3000              # the default; fixed for the cluster's lifetime

memtx:
  memory: 536870912               # 512 MiB per instance (default 256 MiB)

groups:
  storages:
    app:
      file: storage.lua
    sharding:
      roles: [storage]
    replication:
      failover: manual            # each replicaset's `leader` below is its writable master
    replicasets:
YAML
for rs in "$@"; do
	name=${rs%%=*}
	weight=$(case $rs in *=*) echo "${rs#*=}" ;; *) echo 1 ;; esac)
	cat <<YAML
      storage-$name:
        leader: storage-$name-001
        sharding:
          weight: $weight
        instances:
          storage-$name-001:
            iproto: { listen: [{ uri: 'storage-$name-001:3301' }] }
          storage-$name-002:
            iproto: { listen: [{ uri: 'storage-$name-002:3301' }] }
YAML
done
cat <<'YAML'
  routers:
    app:
      file: router.lua
    sharding:
      roles: [router]
    replicasets:
      router-a:
        instances:
          router-a-001:
            iproto: { listen: [{ uri: 'router-a-001:3301' }] }
YAML
