# -*- mode: ruby -*-
# vi: set ft=ruby :

# Minimal Vagrantfile example with virtualbox

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"

    config.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       vb.gui = false

       # Customize the amount of memory on the VM:
       vb.memory = "2048"
     end

  end
