version: "3.9"

services:
  # Server-1
  clickhouse-server-01:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        CLICKHOUSE_VERSION: "22.1"
    image: clickhouse-with-keeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    container_name: clickhouse-server-01
    hostname: ch01
    volumes:
      - ./sql:/ch-replica-sql # sql files
