# -*- mode: ruby -*-
# vi: set ft=ruby :

# Development Vagrantfile example for ClickHouse
# Required Plugins:
# vagrant plugin install vagrant-timezone


$clickhouse_provision = <<-SHELL

  # Install prerequisite packages
  apt install -y apt-transport-https ca-certificates curl gnupg

  # Download the ClickHouse GPG key and store it in the keyring
  curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg

  # Get the system architecture
  ARCH=$(dpkg --print-architecture)

  # Add the ClickHouse repository to apt sources
  echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg arch=${ARCH}] https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list

  # Update apt package lists
  apt-get update

  # Install ClickHouse
  apt update
  DEBIAN_FRONTEND=noninteractive apt install -y clickhouse-server clickhouse-client
  clickhouse-server --version

  # start ClickHouse Server if it is not running
  systemctl start clickhouse-server
  systemctl status clickhouse-server

SHELL


Vagrant.configure("2") do |config|

  # set timezone for all VMs
  config.timezone.value = "UTC"

  # define a server vagrant machine
  config.vm.define "clickhouse01", autostart: true do |chserver|

    # hostname for the VM
    chserver.vm.hostname = "clickhouse01-noble"
    # image for the VM
    # See all images at https://app.vagrantup.com/boxes/search
    chserver.vm.box = "bento/ubuntu-24.04"

    # Use Virtual Box as the provider
    chserver.vm.provider "virtualbox" do |vb|
      #  Virtual Box Settings - GUI for the VM
      vb.gui = false
      #  Virtual Box Settings - Name for the VM
      vb.name = "Ubuntu 24.04 - ClickHouse Server - 01"
      #  Virtual Box Settings - Allocated memory
      vb.memory = "4096"
    end

    # provision scripts
    chserver.vm.provision "shell", inline: $clickhouse_provision

  end

end
