version: "3.9"

services:
  # Generic ClickHouse Service
  clickhouse:
    image: "clickhouse/clickhouse-server:22.1"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # ports: # port-mapping to access the server from the host machine (otherwise, it's not needed)
    #  - 18123:8123 # http port
    #  - 19000:9000 # native port
    #  - 19009:9009 #
    volumes:
      - ./config.d/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml # zookeeper/keeper client configs
      - ./config.d/clusters.xml:/etc/clickhouse-server/config.d/clusters.xml # cluster configs
      - ./sql:/ch-replica-sql # sql files
    networks:
      - clickhouse
