version: "3.9"

services:
  # Server-1
  clickhouse-server-01:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-server-01
    hostname: ch01
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      # port-mapping to access the server from the host machine (otherwise, it's not needed)
      - 18123:8123 # http port
      - 19000:9000 # native port
      - 19009:9009 # 
    volumes:
      - ./config.d/replicas.xml:/etc/clickhouse-server/config.d/replicas.xml # clickhouse-server configs
      - ./sql:/ch-replica-sql # sql files
    networks:
      - clickhouse
  # Server-2
  clickhouse-server-02:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-server-02
    hostname: ch02
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      # port-mapping to access the server from the host machine (otherwise, it's not needed)
      - 28123:8123 # http port
      - 29000:9000 # native port
      - 29009:9009 # 
    volumes:
      - ./config.d/replicas.xml:/etc/clickhouse-server/config.d/replicas.xml # clickhouse-server configs
      - ./sql:/ch-replica-sql # sql files
      - ./setup/setup-ch-tables.sh:/docker-entrypoint-initdb.d/setup-ch-tables.sh # setup clickhouse tables
    networks:
      - clickhouse
  # Server-3
  clickhouse-server-03:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse-server-03
    hostname: ch03
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      # port-mapping to access the server from the host machine (otherwise, it's not needed)
      - 38123:8123 # http port
      - 39000:9000 # native port
      - 39009:9009 # 
    volumes:
      - ./config.d/replicas.xml:/etc/clickhouse-server/config.d/replicas.xml # clickhouse-server configs
      - ./sql:/ch-replica-sql # sql files
      - ./setup/setup-ch-tables.sh:/docker-entrypoint-initdb.d/setup-ch-tables.sh # setup clickhouse tables
    networks:
      - clickhouse

networks:
  clickhouse:
    driver: bridge
