-- Table to store user information with autogenerated unique IDs
CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    city STRING NOT NULL,
    name STRING NULL,
    address STRING NULL,
    credit_card STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),
    FAMILY "primary" (id, city, name, address, credit_card)
);

-- Show Table
SHOW COLUMNS FROM users;
SHOW INDEX FROM users;

-- Table to store vehicle information
CREATE TABLE IF NOT EXISTS vehicles (
        id UUID NOT NULL,
        city STRING NOT NULL,
        type STRING,
        owner_id UUID,
        creation_time TIMESTAMP,
        status STRING,
        current_location STRING,
        ext JSONB,
        CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),
        INDEX index_status (status),
        INVERTED INDEX ix_vehicle_ext (ext),
        FAMILY "primary" (id, city, type, owner_id, creation_time, status, current_location, ext)
);

--- Show Table
SHOW INDEX FROM vehicles;

-- Enable vector index
SET CLUSTER SETTING feature.vector_index.enabled = true;

-- Table to store items with vector embeddings
CREATE TABLE IF NOT EXISTS items (
     id uuid DEFAULT gen_random_uuid(),
     embedding VECTOR (1536),
     VECTOR INDEX (embedding)
);

-- Show Table
SHOW COLUMNS FROM items;
SHOW INDEX FROM items;
