version: '3.9'

services:
  # Zookeeper is needed (as of Jan 2022) - but soon it won't be needed
  zookeeper:
    image: zookeeper:3.7
  # Kafka container
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # TOPICS: `test` will have 3 partitions and 1 replica and `test2` will have 1 partition and 1 replica
      KAFKA_CREATE_TOPICS: "test:3:1,test2:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
