# Global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "clickhouse-server"
    static_configs:
      - targets:
          # for serv in {01..11}; do echo clickhouse-server-$serv:8001 ;done
          - "clickhouse-server-01:8001"
          - "clickhouse-server-02:8001"
          - "clickhouse-server-03:8001"
          - "clickhouse-server-04:8001"
          - "clickhouse-server-05:8001"
          - "clickhouse-server-06:8001"
          - "clickhouse-server-07:8001"
          - "clickhouse-server-08:8001"
          - "clickhouse-server-09:8001"
          - "clickhouse-server-10:8001"
          - "clickhouse-server-11:8001"
